# Generated by Django 2.1.8 on 2020-12-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detetction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='file_location',
            field=models.CharField(default=1, max_length=60, verbose_name='file_location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='reason',
            field=models.TextField(verbose_name='reason'),
        ),
    ]
