# Generated by Django 2.1.8 on 2020-12-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detetction', '0003_auto_20201213_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(max_length=1, verbose_name='id'),
        ),
    ]
