# Generated by Django 2.1.8 on 2020-12-15 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detetction', '0004_auto_20201214_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_time'),
        ),
    ]
