# Generated by Django 2.1.8 on 2020-12-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detetction', '0006_remove_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_time'),
        ),
    ]
